name: Deploy to Github Pages

# run when a commit is pushed to "source" branch
on:
  push:
    branches:
    - source

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          
      - name: Super-Linter
        uses: github/super-linter@v4.8.7
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: source
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

    # build website
      - name: Build
        run: hugo --minify

      # push the generated content into the `main` (former `master`) branch.
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main # if your main branch is `master` use that here.
          publish_dir: ./public
